### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by wenyang9319** [adyen-examples/adyen-vue-online-payments#1]
I have followed [usage instruction](https://github.com/adyen-examples/adyen-vue-online-payments#usage) to setup the projects, however I met this CORS issue.
```
Failed to load resource: the server responded with a status of 404 (Not Found)
card:1 Access to fetch at 'https://checkoutshopper-test.adyen.com/checkoutshopper/v1/analytics/log?token=test_TTJ2JBTCMBGRJI4XSNU63Z3OUQHOZ5DQ' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
checkoutshopper-test.adyen.com/checkoutshopper/v1/analytics/log?token=test_TTJ2JBTCMBGRJI4XSNU63Z3OUQHOZ5DQ:1 Failed to load resource: net::ERR_FAILED
contentscript.js:58 <body>​…​</body>​
```

Project is launched on Google Chrome,  I have tried to installed CORS plugin to overwrite the request but it wasn't working.
Below attached is the screenshot.
<img width="1287" alt="Screenshot 2020-12-09 at 6 25 27 PM" src="https://user-images.githubusercontent.com/12107648/101617742-fb6b3f00-3a4b-11eb-98a5-feb3982c1ddd.png">

What can I do in order to run this example project?

**Comment by deepu105** [comment]
Have you setup the client key as per the instructions in Readme. This error is due to missing client key

**Comment by SebastienPoncelet** [comment]
Hello @deepu105 ,

I have provided the client key as instructed in a ".env" file, can see the values having been provided in the utils.js as well. However I still get this error. Is there something else that I've missed?

Thanks!

**Comment by deepu105** [comment]
In your customer area have you added the localhost and port for client key origin?

**Comment by SebastienPoncelet** [comment]
Hello @deepu105 ,

Thanks for the reply. My mistake was having forgotten to add our `http://localhost:8080` as a client key origin.
For anyone else who might face this issue, just go to your Adyen account, access your API credentials and then add your localhost in this section:"Allow Origins".
