### ISSUE TITLE
Upgrade to Web Drop-in v5.0.0

### ISSUE THREAD

**Issue by ThermScissorpunch** [adyen-examples/adyen-vue-online-payments#14]
Hi!

I am currently integrating the web drop-in 5.0.0 in a Vue.js project. Is it possible to upgrade this project so that it uses the v5.0.0 also? It would greatly help me with the integration :-)

**Comment by jillingk** [comment]
Hey!

We are working on updating the project as we speak. If you already want to have a sneak peak, you can lookup the branch [sessions](https://github.com/adyen-examples/adyen-vue-online-payments/tree/sessions). Here we already integrated the new web drop-in and components for Vue.js (note that it is work in progress). Additionally you can go over to the other JS based demo's we have, as all they should all follow roughly the same structure for the payment integration.

Let us know if you run into anything else!

**Comment by gcatanese** [comment]
PR is merged, good job
